name: E2E Tests on PR (Playwright)

on:
  pull_request:
    branches:
      - dev
      - staging
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  run-e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Codebase
        uses: ./.github/actions/setup-codebase
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        id: playwright
        run: |
          set -o pipefail
          npx playwright test --reporter=list --trace=on | tee playwright.log
        continue-on-error: true

      - name: Upload HTML report (for review)
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Comment on PR with result
        if: ${{ !cancelled() }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## Playwright E2E Results
            **Status:** ${{ steps.playwright.outcome == 'success' && '✅ Passed' || '❌ Failed' }}
            - View full report: [Artifacts > playwright-report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Fail workflow if tests failed
        if: ${{ steps.playwright.outcome == 'failure' }}
        run: exit 1
